### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by yoricya** [fermarsan/aixt#149]
```log
aroslav@iMacPro-Aroslav aixt-0.1.8 % make    
/Users/aroslav/vlang/v -o ./aixt ./src
================== C compilation error (from cc): ==============
cc:        |                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc: /tmp/v_501/aixt.01JEZENHPABP751S08S5B79N96.tmp.c:77002:113: error: passing 'v__ast__Expr' (aka 'struct v__ast__Expr') to parameter of incompatible type 'v__ast__Expr *' (aka 'struct v__ast__Expr *'); take the address with &
cc:  77002 |                                 string var_value = Array_string_join(aixt_cgen__Gen_ast_node(gen, v__ast__Expr_to_sumtype_v__ast__Node/*Q*/(((v__ast__CastExpr*)__as_cast((node.expr)._v__ast__CastExpr,(node.expr)._typ, 195))->expr)), _SLIT(""));
cc:        |                                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc:        |                                                                                                                                             &
cc: /tmp/v_501/aixt.01JEZENHPABP751S08S5B79N96.tmp.c:11981:73: note: passing argument to parameter 'x' here
cc:  11981 | v__ast__Node v__ast__Expr_to_sumtype_v__ast__Node/*ISEE*/(v__ast__Expr* x) {
cc:        |                                                                         ^
cc: /tmp/v_501/aixt.01JEZENHPABP751S08S5B79N96.tmp.c:77571:111: error: passing 'v__ast__Expr' (aka 'struct v__ast__Expr') to parameter of incompatible type 'v__ast__Expr *' (aka 'struct v__ast__Expr *'); take the address with &
cc:  77571 |                 string var_value = Array_string_join(aixt_cgen__Gen_ast_node(gen, v__ast__Expr_to_sumtype_v__ast__Node/*Q*/(((v__ast__CastExpr*)__as_cast((node.expr)._v__ast__CastExpr,(node.expr)._typ, 195))->expr)), _SLIT(""));
cc:        |                                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc:        |                                                                                                                             &
... (the original output was 50 lines long, and was truncated to 12 lines)
================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
make: *** [aixt] Error 1
aroslav@iMacPro-Aroslav aixt-0.1.8 % 
```

This is really V bug?

**Comment by yoricya** [comment]
```log
lima-alpine:~/aixt$ make
/home/aroslav.linux/vlinux/v -o ./aixt ./src
================== C compilation error (from tcc): ==============
cc: /tmp/v_501/aixt.01JEZFZBR88ME09PB8Z0TK4PTA.tmp.c:77197: error: cannot convert 'struct v__ast__Expr' to 'struct v__ast__Expr *'
=================================================================
(You can pass `-cg`, or `-show-c-output` as well, to print all the C error messages).
builder error: 
==================
C error found. It should never happen, when compiling pure V code.
This is a V compiler bug, please report it using `v bug file.v`,
or goto https://github.com/vlang/v/issues/new/choose .
You can also use #help on Discord: https://discord.gg/vlang .
make: *** [Makefile:10: aixt] Error 1
lima-alpine:~/aixt$ 
```

on alpine linux same problem

**Comment by fermarsan** [comment]
Yes it was an V bug.

I already report it and V's development team solved it:
[https://github.com/vlang/v/issues/23387](https://github.com/vlang/v/issues/23387)

try to build it again

**Comment by fermarsan** [comment]
Aixt already works with V 0.4.9
